name: "Trigger Auto Deployment"

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    deploy:
        name: "Trigger Auto Deployment to Vercel"
        runs-on: ubuntu-latest
        steps:
            - name: "Curl request"
              shell: bash
              env: 
                TRIGGER_DEPLOYMENT_URL: ${{ secrets.TRIGGER_DEPLOYMENT_URL }}
              run: curl -X POST "$TRIGGER_DEPLOYMENT_URL"
